### ISSUE TITLE
exception when trying to wrap to the window size

### ISSUE THREAD

**Issue by samdmarshall** [CocoaPods/Cork#9]
System `ruby` on 10.11.6

```
$ ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
```

System `gem` on 10.11.6

```
$ gem --version
2.0.14.1

```

Stacktrace:

```
/Users/Samantha/.gem/ruby/2.0.0/gems/cork-0.1.0/lib/cork/board.rb:333:in `wrap_string': undefined method `winsize' for #<IO:<STDOUT>> (NoMethodError)
    from /Users/Samantha/.gem/ruby/2.0.0/gems/cork-0.1.0/lib/cork/board.rb:80:in `puts_indented'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-plugins-0.9.1/lib/claide/command/plugins_helper.rb:79:in `block in print_plugin'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/cork-0.1.0/lib/cork/board.rb:234:in `title'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-plugins-0.9.1/lib/claide/command/plugins_helper.rb:78:in `print_plugin'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-plugins-0.9.1/lib/claide/command/plugins/list.rb:27:in `block (2 levels) in run'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-plugins-0.9.1/lib/claide/command/plugins/list.rb:26:in `each'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-plugins-0.9.1/lib/claide/command/plugins/list.rb:26:in `block in run'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/cork-0.1.0/lib/cork/board.rb:234:in `title'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-plugins-0.9.1/lib/claide/command/plugins/list.rb:25:in `run'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/danger-0.10.1/bin/danger:5:in `<top (required)>'
    from /Users/Samantha/.gem/ruby/2.0.0/bin/danger:23:in `load'
    from /Users/Samantha/.gem/ruby/2.0.0/bin/danger:23:in `<main>'
```

**Comment by segiddins** [comment]
looks like we may need to `require 'io-console'` somewhere
